### ISSUE TITLE
Package names should be one word without underscores

### ISSUE THREAD

**Issue by dacb** [gdc3000/wa_collisions#10]
Any chance you can remove that underscore without breaking everything?

**Comment by SalikWarsi** [comment]
I am really sorry about that. We could change it but it is used in a few places in the jupyter notebooks, and we are worried changing it now might break something. Also it's the name of the github repo as well, so to maintain uniformity we would have to consider changing that. We will definitely keep this in mind the next time we create a package.

**Comment by emontague** [comment]
We've fixed the module name in branch. We have successfully run the unittests and are testing the python modules. Since this project is due in couple hours, we are not planning merge this. 

https://github.com/gdc3000/wa_collisions/tree/module_name_change
