### ISSUE TITLE
unable to import error

### ISSUE THREAD

**Issue by SalikWarsi** [gdc3000/wa_collisions#4]
pylint on test file gives unable to import error. However the test runs fine when called using python

**Comment by emontague** [comment]
I'm having a similar error. I'm also not able to import modules that are not in the same directory.

**Comment by emontague** [comment]
You need to run the tests in the top directory:
PS C:\Users\Libby\Documents\DATA_515\class_project\wa_collisions> python -m unittest

**Comment by emontague** [comment]
You can import from a lower module. 
This will work for calling the tests from the top of the module. 
 
emontague:/class_project/wa_collisions$ ls
appveyor.yml  doc  examples  LICENSE  Makefile  README.md  requirements.txt  scripts  setup.py  vehicle_collisions  wa_collisions
emontague:/class_project/wa_collisions$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from wa_collisions.sample_module import hello_world
>>> hello_world('Test')
hello world from Test
