### ISSUE TITLE
questions on data integration

### ISSUE THREAD

**Issue by jasonfeiwang** [gdc3000/wa_collisions#8]
A couple of thoughts on joining collision data with weather data:

1) limit the time scope of collision data to [2014/01/01/ - Now] -- IEM weather data is from 2014/01/01 on
2) rename column names,  drop non-useful columns, naming convention (lower case with underscore?)  -- should be consistent across all data cleaning modules
3) only one consolidated data set or one for each use case?

**Comment by emontague** [comment]
1. The larger scope is needed for some of our methods. We will add in an optional parameter. 
2. We'll need to confirm that this works with all of the code. 
3. I think we should keep the same data set for all to make sure that we're using consistent data.
